import type { NextPage } from 'next'
import Head from 'next/head'
import Activity from '../components/Activity'
import Membership from '../components/Membership'
import Programme from '../components/Programme'

const Home: NextPage = () => {
  return (
    <div className='text-center'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='flex flex-row justify-evenly'>
        <Activity />
        {/* <Membership /> */}
      </div>
      <div>
        <Programme />
      </div>
    </div>
  )
}

export default Home
