import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import Listing from "../components/Listing";
import { Data } from "./api/listings";
import { useRouter } from "next/router";

const Listings: NextPage = () => {
  const [listings, setListings] = useState<Data[]>([]);
  const router = useRouter();
  const routerData = router.query;

  useEffect(() => {
    console.log(routerData.name)
    fetch(`/api/listings/${routerData.name}`)
      .then((res) => res.json())
      .then((data) => {
        setListings(data);
      });
  }, []);

  const listingsComponent = listings.map(item => {
    return <Listing key={item.id} details={item} />
  })

  return (
    <div className="text-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-row">
        <div className="flex flex-col justify-start flex-1">
          {listingsComponent}
        </div>
        <div className="flex-1"></div>
      </div>
    </div>
  );
};

export default Listings;
